main:
  - name: Home
    url: ""
    weight: 1
  - name: About
    url: "#about"
    weight: 2
  - name: News
    url: "#resume"
    weight: 3
  - name: Spotlight
    url: "#product"
    weight: 4
  - name: Books
    url: "#service"
    weight: 5
  - name: Testimonials
    url: "#testimonial"
    weight: 6
  - name: Blog
    url: "#blog"
    weight: 7
sitemap:
  - name: Home
    url: ""
    weight: 1
  - name: Contact Us
    url: "contact"
    weight: 2
  - name: Books
    url: "products"
    weight: 3
  - name: Blog
    url: "blog"
    weight: 4
