titleSeparator: "-"
titleAddition: Published works of Kirk Ward Robinson
description: >-
  Kirk Ward Robinson was born and raised in South Texas and has since
  lived in every Timezone in the continental United States.
images:
  - favicon.ico
ogLocale: en_US
titleHome: Kirk Ward Robinson
twitterSite: "@kirkwardrobinson"
twitterCreator: "@kirkwardrobinson"
schemaType: Organization
schemaName: krob
schemaAuthor: J.Red Robinson
schemaAuthorTwitter: "https://twitter.com/drawpdeadredd"
schemaAuthorLinkedIn: "https://www.linkedin.com/in/JarredRobinson/"
schemaAuthorGitHub: "https://github.com/drpdead"
schemaLocale: en-US
schemaLogo: farmlogo.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: farmlogo.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: "https://twitter.com/"
schemaLinkedIn: ""
schemaGitHub: "https://github.com/drpdead/krob"
themeColor: "#319955"
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "320"
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - "480"
  - "720"
  - "1080"
  - "1280"
  - "1600"
  - "2048"
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
alert: true
alertDismissable: true
alertText: >-
  This site accepts cookies. To turn off this feature click here →<a class="alert-link"
  href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">site-settings</a>
blogPageURL: blog
contactLink: contact
copyright: All right reserved copyright © Kirk Ward Robinson 2024
footerLogo: images/site-navigation/logo.png
footerContact:
  topTitle: Book KWR for insightful talks and personalized signings
  title: Experience Kirk Ward Robinson Live!
  button: Inquire within
fabformURL: "https://fabform.io/f/JpTXRUa"
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
logo: images/farmlogo.png
address:
  address: "Below the Mason-Dixon, Tennessee"
  email: info@kirkwardrobinson.com
  openingHours: Open from 4am to 6pm (close at 5pm Sundays)
  phone: (+1) 6158675309
map:
  APIkey: YOUR GOOGLE MAP API
  latitude: "23.7783741"
  longitude: "90.3746808"
  pinImage: images/pin.png
social:
  - icon: fa-facebook-official
    url: "https://www.facebook.com/"
    weight: 1
  - icon: fa-linkedin-square
    url: "https://www.linkedin.com/"
    weight: 2
  - icon: fa-pinterest-square
    url: "https://www.pinterest.com/"
    weight: 3
  - icon: fa-twitter-square
    url: "https://twitter.com/"
    weight: 4
_template: parameters_template
